services:
  mudextensions:
    image: ghcr.io/codebeamorg/codebeam.mudblazor.extensions:dev
    container_name: mudextensions
    restart: unless-stopped
    networks:
      - edge

networks:
  edge:
    external: true
