<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <RootNamespace>MudExtensions.Docs.Wasm</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.*" PrivateAssets="all" />
  </ItemGroup>

	<!--<ItemGroup>
		<BlazorWebAssemblyLazyLoad Include="zxing.dll" />
	</ItemGroup>-->
	
  <ItemGroup>
    <ProjectReference Include="..\..\src\CodeBeam.MudBlazor.Extensions\CodeBeam.MudBlazor.Extensions.csproj" />
    <ProjectReference Include="..\..\docs\CodeBeam.MudBlazor.Extensions.Docs\CodeBeam.MudBlazor.Extensions.Docs.csproj" />
  </ItemGroup>

	<Target Name="CopyXmlDocToWwwRoot" AfterTargets="Build">
		<ItemGroup>
			<_XmlDoc Include="..\..\src\CodeBeam.MudBlazor.Extensions\bin\$(Configuration)\$(TargetFramework)\CodeBeam.MudBlazor.Extensions.xml" />
		</ItemGroup>

		<Copy
		  SourceFiles="@(_XmlDoc)"
		  DestinationFolder="wwwroot"
		  SkipUnchangedFiles="true"
		  Condition="Exists('%(Identity)')" />
	</Target>


	<ItemGroup>
    <Content Update="wwwroot\favicon.ico">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
