<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Version>9.0.0-rc.1</Version>
		<Title>CodeBeam.MudBlazor.Extensions</Title>
		<PackageId>CodeBeam.MudBlazor.Extensions</PackageId>
		<Authors>CodeBeam</Authors>
		<Company>CodeBeam</Company>
		<Description>MudBlazor extension components from contributors. Includes 30+ components and utilities.</Description>
		<Copyright>CodeBeam OpenSource MIT</Copyright>
		<PackageIcon>Mud_Secondary.png</PackageIcon>
		<PackageProjectUrl>https://mudextensions.codebeam.org/</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions</RepositoryUrl>
		<PackageTags>Blazor; MudBlazor; Component; Extension; Material3; Animate; Stepper; ComboBox; Select; List; Loading; Gallery; ChipField; Transfer; Barcode; QR; SpeedDial; RangeSlider; Teleport</PackageTags>
		<RootNamespace>MudExtensions</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<IsTrimmable>true</IsTrimmable>
		<TrimMode>link</TrimMode>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<SassCompilerEnableWatcher>false</SassCompilerEnableWatcher>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<!--Uncomment it and build again when you change the CSS/SASS files, currently it fails the CI process-->
	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<!--<PackageReference Include="MudBlazor.SassCompiler" Version="2.0.7">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>-->
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MudBlazor" Version="9.0.0-rc.1" />
	</ItemGroup>

	<Target Name="MinifyMudExtensionsJs" AfterTargets="Build" Condition="'$(CI)' != 'true'&#xD;&#xA;               AND '$(TargetFramework)' == 'net10.0'&#xD;&#xA;               AND Exists('TScripts/MudExtensions.js')">
		<Message Importance="high" Text="Minifying MudExtensions.js → MudExtensions.min.js" />
		<Exec WorkingDirectory="$(SolutionDir)" Command="dotnet run --project utilities\CodeBeam.MudBlazor.Extensions.JsMinifier\CodeBeam.MudBlazor.Extensions.JsMinifier.csproj --configuration $(Configuration)" />
	</Target>

	<ItemGroup>
		<Content Remove="sasscompiler.json" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>CodeBeam.MudBlazor.Extensions.UnitTests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
	
	<ItemGroup>
		<None Include="Mud_Secondary.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
