<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Version>9.0.0</Version>
		<Title>CodeBeam.MudBlazor.Extensions.Code</Title>
		<Authors>CodeBeam</Authors>
		<Company>CodeBeam</Company>
		<Description>
CodeViewer Component for MudBlazor and CodeBeam.MudBlazor.Extensions
Requires CodeBeam.MudBlazor.Extensions.
https://www.nuget.org/packages/CodeBeam.MudBlazor.Extensions
		</Description>
		<Copyright>CodeBeam OpenSource MIT</Copyright>
		<PackageIcon>Mud_Secondary.png</PackageIcon>
		<PackageProjectUrl>https://mudextensions.codebeam.org/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions</RepositoryUrl>
		<PackageTags>Blazor; MudBlazor; Component; Extension; CodeViewer</PackageTags>
		<RootNamespace>MudExtensions</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<IsTrimmable>true</IsTrimmable>
		<TrimMode>link</TrimMode>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CodeBeam.MudBlazor.Extensions" Version="9.0.0-rc.1" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Mud_Secondary.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

</Project>
