<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>MudExtensions.Docs</RootNamespace>
	</PropertyGroup>


	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.*" />
		<PackageReference Include="MudBlazor" Version="9.0.0-preview.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CodeBeam.MudBlazor.Extensions.CsvMapper\CodeBeam.MudBlazor.Extensions.CsvMapper.csproj" />
		<ProjectReference Include="..\CodeBeam.MudBlazor.Extensions.Qr\CodeBeam.MudBlazor.Extensions.Qr.csproj" />
		<ProjectReference Include="..\CodeBeam.MudBlazor.Extensions\CodeBeam.MudBlazor.Extensions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="Components\FixedTransition.razor">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Update="Pages\Index.razor">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Pages/Components/**" />
	</ItemGroup>

</Project>
