<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Version>9.1.0</Version>
		<Title>CodeBeam.MudBlazor.Extensions.Csv</Title>
		<Authors>CodeBeam</Authors>
		<Company>CodeBeam</Company>
		<Description>
			CsvMapper Component for MudBlazor and CodeBeam.MudBlazor.Extensions
			Requires CodeBeam.MudBlazor.Extensions.
			https://www.nuget.org/packages/CodeBeam.MudBlazor.Extensions
		</Description>
		<Copyright>CodeBeam OpenSource MIT</Copyright>
		<PackageIcon>Mud_Secondary.png</PackageIcon>
		<PackageProjectUrl>https://mudextensions.codebeam.org/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions</RepositoryUrl>
		<PackageTags>Blazor; MudBlazor; Component; Extension; Csv; Mapper;</PackageTags>
		<RootNamespace>MudExtensions</RootNamespace>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="CodeBeam.MudBlazor.Extensions" Version="9.1.0" />
	  <PackageReference Include="CsvHelper" Version="33.1.0" />
	</ItemGroup>


	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Mud_Secondary.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
